// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Alerting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagementZoneV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyBindingsV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyBoundary) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2LogsPipelinegroups) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2LogsPipelines) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2LogsRouting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2SpansPipelinegroups) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2SpansPipelines) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *V2SpansRouting) Hub() {}
