// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Alerting.
func (mg *Alerting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ManagementZone),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ManagementZoneRef,
		Selector:     mg.Spec.ForProvider.ManagementZoneSelector,
		To: reference.To{
			List:    &ManagementZoneV2List{},
			Managed: &ManagementZoneV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ManagementZone")
	}
	mg.Spec.ForProvider.ManagementZone = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ManagementZoneRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ManagementZone),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ManagementZoneRef,
		Selector:     mg.Spec.InitProvider.ManagementZoneSelector,
		To: reference.To{
			List:    &ManagementZoneV2List{},
			Managed: &ManagementZoneV2{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ManagementZone")
	}
	mg.Spec.InitProvider.ManagementZone = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ManagementZoneRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PolicyBindingsV2.
func (mg *PolicyBindingsV2) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Group),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupRef,
		Selector:     mg.Spec.ForProvider.GroupSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Group")
	}
	mg.Spec.ForProvider.Group = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Policy); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Policy[i3].Boundaries),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Policy[i3].BoundariesRefs,
			Selector:      mg.Spec.ForProvider.Policy[i3].BoundariesSelector,
			To: reference.To{
				List:    &PolicyBoundaryList{},
				Managed: &PolicyBoundary{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Policy[i3].Boundaries")
		}
		mg.Spec.ForProvider.Policy[i3].Boundaries = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Policy[i3].BoundariesRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Policy); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Policy[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Policy[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Policy[i3].IDSelector,
			To: reference.To{
				List:    &PolicyList{},
				Managed: &Policy{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Policy[i3].ID")
		}
		mg.Spec.ForProvider.Policy[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Policy[i3].IDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Group),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupRef,
		Selector:     mg.Spec.InitProvider.GroupSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Group")
	}
	mg.Spec.InitProvider.Group = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Policy); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Policy[i3].Boundaries),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Policy[i3].BoundariesRefs,
			Selector:      mg.Spec.InitProvider.Policy[i3].BoundariesSelector,
			To: reference.To{
				List:    &PolicyBoundaryList{},
				Managed: &PolicyBoundary{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Policy[i3].Boundaries")
		}
		mg.Spec.InitProvider.Policy[i3].Boundaries = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Policy[i3].BoundariesRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Policy); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Policy[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Policy[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Policy[i3].IDSelector,
			To: reference.To{
				List:    &PolicyList{},
				Managed: &Policy{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Policy[i3].ID")
		}
		mg.Spec.InitProvider.Policy[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Policy[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this V2LogsPipelinegroups.
func (mg *V2LogsPipelinegroups) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.MemberPipelines),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.MemberPipelinesRefs,
		Selector:      mg.Spec.ForProvider.MemberPipelinesSelector,
		To: reference.To{
			List:    &V2LogsPipelinesList{},
			Managed: &V2LogsPipelines{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemberPipelines")
	}
	mg.Spec.ForProvider.MemberPipelines = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.MemberPipelinesRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.MemberPipelines),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.MemberPipelinesRefs,
		Selector:      mg.Spec.InitProvider.MemberPipelinesSelector,
		To: reference.To{
			List:    &V2LogsPipelinesList{},
			Managed: &V2LogsPipelines{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MemberPipelines")
	}
	mg.Spec.InitProvider.MemberPipelines = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.MemberPipelinesRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this V2LogsRouting.
func (mg *V2LogsRouting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.RoutingEntries); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef,
				Selector:     mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDSelector,
				To: reference.To{
					List:    &V2LogsPipelinesList{},
					Managed: &V2LogsPipelines{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID")
			}
			mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.RoutingEntries); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef,
				Selector:     mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDSelector,
				To: reference.To{
					List:    &V2LogsPipelinesList{},
					Managed: &V2LogsPipelines{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID")
			}
			mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this V2SpansPipelinegroups.
func (mg *V2SpansPipelinegroups) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.MemberPipelines),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.MemberPipelinesRefs,
		Selector:      mg.Spec.ForProvider.MemberPipelinesSelector,
		To: reference.To{
			List:    &V2SpansPipelinesList{},
			Managed: &V2SpansPipelines{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemberPipelines")
	}
	mg.Spec.ForProvider.MemberPipelines = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.MemberPipelinesRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.MemberPipelines),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.MemberPipelinesRefs,
		Selector:      mg.Spec.InitProvider.MemberPipelinesSelector,
		To: reference.To{
			List:    &V2SpansPipelinesList{},
			Managed: &V2SpansPipelines{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MemberPipelines")
	}
	mg.Spec.InitProvider.MemberPipelines = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.MemberPipelinesRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this V2SpansRouting.
func (mg *V2SpansRouting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.RoutingEntries); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef,
				Selector:     mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDSelector,
				To: reference.To{
					List:    &V2SpansPipelinesList{},
					Managed: &V2SpansPipelines{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID")
			}
			mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.RoutingEntries); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef,
				Selector:     mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDSelector,
				To: reference.To{
					List:    &V2SpansPipelinesList{},
					Managed: &V2SpansPipelines{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID")
			}
			mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.RoutingEntries[i3].RoutingEntry[i4].PipelineIDRef = rsp.ResolvedReference

		}
	}

	return nil
}
